auction/urls.py
from django.urls import path
from . import views
from .views import IndexView, AllListingsView

app_name = "auction"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("all/", AllListingsView.as_view(), name="all_listings"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("createListing", views.createlisting, name="createListing"),
    path("details/<int:id>", views.details, name="details"),
    path("categories", views.categories, name="categories"),
    path("filter/<str:name>", views.filter_by_category, name="filter"),
    path("comment/<int:id>", views.comment, name="comment"),
    path("bid/<int:id>", views.place_bid, name="bid"),
    path("end/<int:item_id>", views.auction_ending, name="end"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("watch", views.watch, name="watch")
]

auction_django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auction.urls"))
]

auction/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    watchlist = models.ManyToManyField("Auction", blank=True, related_name="watchlist")


class Auction(models.Model):
    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    start_bid = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.URLField(blank=True)
    active = models.BooleanField()

    def __str__(self):
        return (f"{self.id} : {self.title} in {self.category.title}\n"
                f"Posted at : {self.date}\n"
                f"Value : {self.start_bid}\n"
                f"Description : {self.description}\n"
                f"Posted By : {self.user.username} Active Status: {self.active}")

class Category(models.Model):
    name = models.CharField(max_length=255, default="Unknown")
    title = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.id}: {self.title}"

class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    bid_value = models.DecimalField(max_digits=10, decimal_places=2)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.id} : {self.user.username} bid {self.bid_value} on {self.auction.title} at {self.date}"



class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    comment_value = models.CharField(max_length=100)

    def __str__(self):
        return (f"{self.id} : {self.user.username} "
                f"commented on {self.auction.title} posted by {self.auction.user.username} "
                f"at {self.date} : {self.comment_value}")

auction/views.py
from django.urls import reverse
from django.db.models import Max
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import render
from django.views import generic
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, HttpRequest
from django.contrib.auth import authenticate, login, logout
from django.views.decorators.csrf import csrf_exempt

from auction.models import Auction, User, Category, Bid, Comment


class IndexView(generic.ListView):
    model = Auction
    template_name = "auction/index.html"
    context_object_name = "objects"

    def get_queryset(self):
        return Auction.objects.filter(active=True)


class AllListingsView(generic.ListView):
    model = Auction
    template_name = "auction/index.html"
    context_object_name = "objects"

    def get_queryset(self):
        return Auction.objects.all()

def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auction/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auction/login.html")


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

@csrf_exempt
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auction/register.html", {
                "message": "Passwords must match."
            })

        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auction/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auction:index"))
    else:
        return render(request, "auction/register.html")


@login_required
def createlisting(request):
    if request.method == 'POST':
        title = request.POST["title"]
        description = request.POST["description"]
        startbid = request.POST["startBid"]
        category = Category.objects.get(id=request.POST["category"])
        user = request.user
        imageurl = request.POST["url"]
        if imageurl == '':
            imageurl = "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/300px-No_image_available.svg.png"
        listing = Auction.objects.create(
            name=title, category=category, date=timezone.now(), startbid=startbid, description=description, user=user, imageurl=imageurl, active=True)
        listing.save()
        return HttpResponseRedirect(reverse("index"))
    return render(request, "auction/createListing.html", {
        'categories': Category.objects.all()
    })



def details(request: HttpRequest, pk: int) -> HttpResponse:
    item = Auction.objects.get(pk=pk)
    bids = Bid.objects.filter(auctionListing=item)
    comments = Comment.objects.filter(auctionListing=item)
    value = bids.aggregate(Max("bid_value"))["bid_value__max"]
    bid = None
    if value is not None:
        bid = Bid.objects.filter(bidValue=value)[0]
    return render(request, "auction/details.html", {
        "item": item,
        "bids": bids,
        "comments": comments,
        "bid": bid
    })


def categories(request):
    if request.method == 'POST':
        category = request.POST["category"]
        new_category, created = Category.objects.get_or_create(
            name=category.lower())
        if created:
            new_category.save()
        else:
            messages.warning(request, "Category already Exists!")
        return HttpResponseRedirect(reverse("categories"))
    return render(request, "auction/categories.html", {
        'categories': Category.objects.all()
    })


def filter_by_category(request: HttpRequest, name: str) -> HttpResponse:
    category = Category.objects.get(name=name)
    obj = Auction.objects.filter(category=category)
    return render(request, "auction/index.html", {
        "objects": obj
    })

@login_required
def comment(request, pk: int) -> HttpResponse:
    if request.method == 'POST':
        auction = Auction.objects.get(pk=pk)
        user = request.user
        comment_value = request.POST["content"].strip()
        if comment_value != "":
            new_comment = Comment.objects.create(date=timezone.now(
            ), user=user, auction=auction, comment_value=comment_value)
            new_comment.save()
        return HttpResponseRedirect(reverse("details", kwargs={'pk': pk}))
    return HttpResponseRedirect(reverse("index"))


@login_required
def place_bid(request, pk: int) -> HttpResponse:
    if request.method == 'POST':
        auction = Auction.objects.get(pk=pk)
        bid_value = request.POST["bid"]
        args = Bid.objects.filter(auctionListing=auction)
        value = args.aggregate(Max("bidValue"))["bidValue__max"]
        if value is None:
            value = 0
        if float(bid_value) < auction.start_bid or float(bid_value) <= value:
            messages.warning(
                request, f"Bid Higher than: {max(value, auction.start_bid)}!")
            return HttpResponseRedirect(reverse("details", kwargs={'pk': pk}))
        user = request.user
        bid = Bid.objects.create(
            date=timezone.now(), user=user, bidValue=bid_value, auctionListing=auction)
        bid.save()
    return HttpResponseRedirect(reverse("details", kwargs={'pk': pk}))


@login_required
def auction_ending(request, item_id: int) -> HttpResponse:
    auction = Auction.objects.get(id=item_id)
    user = request.user
    if auction.user == user:
        auction.active = False
        auction.save()
        messages.success(
            request, f"Auction for {auction.title} successfully closed!")
    else:
        messages.info(
            request, "You are not authorized to end this listing!")
    return HttpResponseRedirect(reverse("details", kwargs={'id': item_id}))


@login_required
def watchlist(request):
    if request.method == 'POST':
        user = request.user
        auctionlisting = Auction.objects.get(id=request.POST["item"])
        if request.POST["status"] == '1':
            user.watchlist.add(auctionlisting)
        else:
            user.watchlist.remove(auctionlisting)
        user.save()
        return HttpResponseRedirect(
            reverse("details", kwargs={'id': auctionlisting.id}))
    return HttpResponseRedirect(reverse("index"))


@login_required
def watch(request):
    user = request.user
    obj = user.watchlist.all()
    return render(request, "auction/index.html", {
        "objects": obj
    })


templates/auction/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEJho3v6o3dROp1j5cFjlf1g2z6wF6SFP52g9P2M9Jg5Ijb7y3IBlZ0j6tkR7" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Baloo+Da+2&display=swap" rel="stylesheet">
    <!-- Static CSS -->
    <link href="{% static 'auction/styles.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light sticky-top py-3">
        <div class="container">
            <a class="navbar-brand" href="{% url 'auction:all_listings' %}">Auctions</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auction:index' %}">Active Listings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auction:categories' %}">Categories</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auction:watch' %}">
                            Watchlist <span class="badge bg-light text-dark">{{ user.watchlist.all.count }}</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auction:createListing' %}">Create Listing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            Signed in as <strong>{{ user.username }}</strong>.
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auction:logout' %}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auction:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auction:register' %}">Register</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <hr>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
</body>

</html>

templates/auction/categories.html
{% extends "auction/base.html" %}

{% block title %}
Categories
{% endblock %}

{% block body %}
<div class="grid-container text-center">
    {% for category in categories %}
    <a href="{% url 'auction:filter' category.title %}">
        <div class="grid-item">
            {{ category.title|title }}
        </div>
    </a>
    {% endfor %}
</div>

{% if user.is_authenticated %}
<div class="add-category">
    {% if messages %}
    {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
    {% endif %}
    <form action="{% url 'auction:categories' %}" method="post">
        {% csrf_token %}
        <div class="row">
            <div class="form-group col">
              <label>
                <input type="text" name="category" class="form-control category-input">
              </label>
            </div>
            <button class="gradient-button category col">Add new Category</button>
        </div>
    </form>
</div>
{% endif %}

{% endblock %}

templates/auction/createlisting.html
{% extends "auction/base.html" %}

{% block title %}
Create Listing
{% endblock %}

{% block body %}

<div class="pt-4 mt-4">
    <form action="{% url 'auction:createListing' %}" method="post">
        {% csrf_token %}
        <div class="form-row form-group mt-2">
            <div class="col">
                <label for="title">Title</label>
              <label>
                <input autofocus type="text" placeholder="Enter Title" name="title" class="form-control">
              </label>
            </div>
            <div class="col">
                <label for="startBid">Starting Bid</label>
              <label>
                <input type="number" name="startBid" class="form-control" placeholder="0.0" step=".01">
              </label>
            </div>
        </div>

        <div class="form-group mt-2">
            <label for="description">Description</label>
          <label>
<textarea class="form-control" name="description" rows="3"
    placeholder="Enter Description of Product"></textarea>
          </label>
        </div>
        <div class="form-row form-group mt-2">
            <div class="col">
                <label for="url">Image Url</label>
              <label>
                <input type="url" placeholder="Enter Image Url" name="url" class="form-control">
              </label>
            </div>
            <div class="col">
                <label for="category">Category</label>
              <label>
                <select class="form-control" name="category">
                    {% for category in categories %}
                    <option value={{ category }}>
                        {{ category.title }}
                    </option>
                    {% endfor %}
                </select>
              </label>
            </div>
        </div>
        <div class="text-center">
            <button type="submit" class="gradient-button add-listing">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

templates/auction/details.html
{% extends "auction/base.html" %}

{% block title %}
{{ item.name }}
{% endblock %}

{% block body %}
<div class="container detail-page">
    <h4 class="mb-3">Listing: <span class="title">{{ item.name }}</span></h4>
    <div class="image">
        <img class="big" src="{{ item.image }}" alt="{{ item.id }}">
    </div>
    <div class="item-description">
        {{ item.description }}
    </div>
    <div class="bid">
        Start Bid : <strong>${{ item.start_bid }}</strong>
    </div>
    {% for bid in bids %}
    <div class="text-center">{{ bid.user.username }} bid <strong>{{ bid.bid_value }}</strong> at
        {{ bid.date|date:'M d, h:i a' }}</div>
    {% empty %}
    <div class="alert alert-warning text-center">
        No Bids Yet!
    </div>
    {% endfor %}

    <section class="my-3">
        {% if messages %}
        {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
        {% endfor %}
        {% endif %}

        {% if bid and item.active == False %}

        <div class="alert alert-dark text-center">
            {% if bid.user.username == user.username %}
            You Won The Auction!
            {% else %}
            <strong>{{ bid.user.username }}</strong> won, with a bid of <strong>${{ bid.bid_value }}</strong>
            {% endif %}
        </div>

        {% endif %}

        {% if item.active and user.is_authenticated %}
        <form action="{% url 'bid' item.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label>
                <input type="number" name="bid" class="form-control" placeholder="Bid" step=".01">
              </label>
            </div>
            <div class="row justify-content-around">
                <button class="btn btn-primary" type="submit">Place Bid</button>
                {% if item.user.username == user.username %}
                <a href="{% url 'end' item.id %}">
                    <button class="btn btn-warning" type="button">End Auction</button>
                </a>
                {% endif %}
            </div>
        </form>
        {% endif %}
    </section>

    <section>
        Details:
        <ul>
            <li>Listed By: <strong>{{ item.user.username }}</strong></li>
            <li>Category: <strong>{{ item.category.title }}</strong></li>
            <li>Listed On: <strong>{{ item.date }}</strong></li>
        </ul>
    </section>

    <section>
        Comments:
        {% for comment in comments %}
        <div class="card comment">
            <div class="card-body">
                <div class="card-title">
                    <strong>{{ comment.user.username }}</strong>: {{ comment.comment_value }}
                </div>
                <div class="card-text">
                    <small>Commented on: <strong>{{ comment.date|date:'M d, h:i a' }}</strong></small>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="alert alert-info mt-2">
            No Comments Yet
        </div>
        {% endfor %}

        {% if user.is_authenticated %}
        <form action="{% url 'comment' item.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label>
                <textarea name="content" rows="4" class="form-control" placeholder="Enter a comment"></textarea>
              </label>
            </div>
            <button class="btn btn-dark py-2 px-4" type="submit">Comment</button>
        </form>

        <form action="{% url 'watchlist' %}" method="post" class="add-category">
            {% csrf_token %}
            <input type="hidden" name="item" value="{{ item.id }}">
            <input type="hidden" value="{% if item in user.watchlist.all %}0{% else %}1{% endif %}" name="status">
            <button class="gradient-button watchlist" type="submit">
                {% if item in user.watchlist.all %}Remove from{% else %}Add to{% endif %} Watchlist
            </button>
        </form>
        {% endif %}
    </section>


</div>
{% endblock %}

templates/auction/index.html
{% extends "auction/base.html" %}

{% block body %}
<h2 class="py-3 m-3">Auction Listings</h2>

<div class="items-list">
    {% for obj in objects %}
    <a href="{% url 'details' obj.id %}">
        <div class="item text-center" {% if obj.active != True %}style="background-color: rgba(255, 220, 220, 0.7);"
            {% endif %}>
            <img src="{{ obj.imageUrl }}" alt="Loading...">
            <div class="details">
                <h5>{{ obj.name }}</h5>
                <h6>Price: $<strong>{{ obj.start_bid }}</strong></h6>
                <small>Created: <strong>{{ obj.date|date:"d-m-Y" }}</strong></small><br>
                {% if obj.active %}
                <span class="badge status--active">Active</span>
                {% else %}
                <span class="badge status--inactive">Ended</span>
                {% endif %}
                {% if obj in user.watchlist.all %}
                <span class="badge status--watching">Watching</span>
                {% else %}
                <span class="badge status--notwatching">Not Watching</span>
                {% endif %}
            </div>
        </div>
    </a>
    {% empty %}
    <div class="alert alert-info text-center p-4 my-4 mx-2">No items Available</div>
    {% endfor %}
</div>
{% endblock %}

templates/auction/login.html
{% extends "auction/base.html" %}

{% block body %}

<div class="container p-4 text-center" style="max-width: 600px;">

    {% if message %}
    <div class="alert alert-danger">{{ message }}</div>
    {% endif %}

    <div class="card inout">
        <div class="card-body m-4">
            <h2 class="card-title">Login</h2>

            <form action="{% url 'auction:login' %}" method="post" class="card-text mb-3">
                {% csrf_token %}
                <div class="form-group">
                  <label>
                    <input autofocus class="form-control" type="text" name="username" placeholder="Username">
                  </label>
                </div>
                <div class="form-group">
                  <label>
                    <input class="form-control" type="password" name="password" placeholder="Password">
                  </label>
                </div>
                <input class="gradient-button login" type="submit" value="Login">
            </form>

            Don't have an account? <a href="{% url 'auction:register' %}"><strong>Register here.</strong></a>
        </div>
    </div>

</div>

{% endblock %}

templates/auction/register.html
{% extends "auction/base.html" %}

{% block body %}
<div class="container p-4 text-center" style="max-width: 600px;">

    {% if message %}
    <div class="alert alert-danger">{{ message }}</div>
    {% endif %}

    <div class="card inout">
        <div class="card-body m-4">
            <h2 class="card-title">Register</h2>

            <form action="{% url 'auction:register' %}" method="post" class="card-text mb-3">
                {% csrf_token %}
                <div class="form-group">
                  <label>
                    <input class="form-control" autofocus type="text" name="username" placeholder="Username">
                  </label>
                </div>
                <div class="form-group">
                  <label>
                    <input class="form-control" type="email" name="email" placeholder="Email Address">
                  </label>
                </div>
                <div class="form-group">
                  <label>
                    <input class="form-control" type="password" name="password" placeholder="Password">
                  </label>
                </div>
                <div class="form-group">
                  <label>
                    <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
                  </label>
                </div>
                <input class="gradient-button register" type="submit" value="Register">
            </form>

            Already have an account? <a href="{% url 'auction:login' %}">Log In here.</a>
        </div>
    </div>

</div>

{% endblock %}